version: '3.1'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:5432"

  web:
    image: odoo:15
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      # - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - PORT=5432
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}

volumes:
  odoo-web-data:
  odoo-db-data:
